collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
color:
  saturation: 0.7126642
  brandStrength: 0.5050125
  lightness: 0.3363202
  brandColors:
    - '#18171C'
    - '#F3F3F3'
    - '#B45C27'
    - '#424B6E'
    - '#E0BDAB'
  rhythmicContrast: 0.1644189
typography_spectrum: 0
layout_spectrum: 1
name: "J. Michael O'Day"
