layout_spectrum: 0.01326353
typography_spectrum: 0.5235543
color:
  saturation: 0.3882674
  lightness: 0.744469
  brandStrength: 0.8043036
  rhythmicContrast: 0.1644189
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
name: "J. Michael O'Day"
